[package]
name = "arm_rstiny"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10"
arm_pl011 = "0.1"
kspin = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
